FROM image-registry.openshift-image-registry.svc:5000/openshift/python:3.11-ubi9

USER root

RUN dnf -y update \
 && dnf -y install python3-pip \
 && dnf -y clean all \
 && rm -rf /var/cache/dnf \
 && pip install pip==24.2 setuptools==80.8.0

USER 1001

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY *.py ./

CMD fastapi run main.py
